/**
 * @file    agriguard_top.sv
 * @brief   AgriGuard-RES Top-Level FPGA Wrapper
 *          Agrionics Systems Co. | iCE40HX8K-TQ144
 *
 * Instantiates and wires together:
 *   1. pdm_decimator  — PDM→PCM 64:1 CIC decimation filter
 *   2. fft_engine     — 256-point Radix-2 SDF pipelined FFT + FAW detector
 *   3. spi_slave      — STM32 register interface + IRQ generation
 *
 * Clock Architecture:
 *   - clk_12mhz: 12 MHz external oscillator on GBIN6 (pin P7)
 *   - pdm_clk_out: 3.072 MHz generated by dividing clk_12mhz by 4
 *     (iCE40 SB_LFOSC or simple counter divider — counter used here
 *      for synthesis portability across nextpnr and iCEcube2)
 *   - All three cores share the 12 MHz domain
 *   - PDM decimator clocked at 12 MHz, pcm_valid output gated at 48kHz rate
 *     (12MHz / 250 = 48kHz — pcm_valid pulses every 250 clk cycles)
 *
 * Signal Flow:
 *   MEMS Mic ──PDM──► pdm_decimator ──PCM──► fft_engine ──FAW──► spi_slave ──IRQ──► STM32
 *   STM32 SPI2 ◄──────────────────────────────────────────────── spi_slave
 *
 * iCE40HX8K Resource Summary (estimated post-synth):
 *   LUTs:  ~3,400 / 7,680  (44%)
 *   BRAMs: ~4 / 32         (12%) — twiddle ROM + delay FIFOs
 *   IOs:   11 / 96         (11%)
 *
 * Timing Target: 12 MHz — easily met on iCE40HX8K (Fmax ~80MHz+ for this logic)
 */

`timescale 1ns / 1ps
`default_nettype none

module agriguard_top (
    // ── CLOCK ────────────────────────────────────────────────────────────────
    input  wire  clk_12mhz,       // 12 MHz crystal oscillator (GBIN6, pin P7)

    // ── RESET (active LOW, driven by STM32 via CRESET_B during boot) ────────
    input  wire  rst_n,           // External reset from STM32 or power-on reset

    // ── PDM MICROPHONE INTERFACE ─────────────────────────────────────────────
    output logic pdm_clk_out,     // 3.072 MHz PDM clock to MEMS microphone
    input  wire  pdm_data,        // 1-bit PDM data from microphone

    // ── SPI SLAVE INTERFACE (STM32 SPI2 master) ──────────────────────────────
    input  wire  spi_sck,
    input  wire  spi_mosi,
    output logic spi_miso,
    input  wire  spi_csn,

    // ── STM32 INTERRUPT OUTPUT ───────────────────────────────────────────────
    output logic fpga_irq         // Active HIGH pulse → STM32 PC13 EXTI13
);

    // =========================================================================
    // PDM CLOCK GENERATION
    // Divide 12 MHz by 4 → 3 MHz  (closest to ideal 3.072 MHz)
    // For exact 3.072 MHz: use 12.288 MHz oscillator on production board.
    // Current 3 MHz introduces 2.4% sample rate error — acceptable for
    // FAW frequency detection (5–12 kHz window is 2.4% tolerant).
    // =========================================================================
    logic [1:0] pdm_clk_div;

    always_ff @(posedge clk_12mhz or negedge rst_n) begin
        if (!rst_n) begin
            pdm_clk_div <= 2'h0;
            pdm_clk_out <= 1'b0;
        end else begin
            pdm_clk_div <= pdm_clk_div + 1'b1;
            pdm_clk_out <= pdm_clk_div[1]; // Toggle every 2 clk → 3 MHz
        end
    end

    // =========================================================================
    // PCM VALID STROBE GENERATION
    // pdm_decimator needs a pcm_valid strobe at 48 kHz.
    // 12 MHz / 250 = 48 kHz — 8-bit counter
    // =========================================================================
    logic [7:0]  pcm_strobe_cnt;
    logic        pcm_strobe;

    localparam logic [7:0] PCM_STROBE_PERIOD = 8'd249; // 250 clocks - 1

    always_ff @(posedge clk_12mhz or negedge rst_n) begin
        if (!rst_n) begin
            pcm_strobe_cnt <= 8'h00;
            pcm_strobe     <= 1'b0;
        end else begin
            if (pcm_strobe_cnt == PCM_STROBE_PERIOD) begin
                pcm_strobe_cnt <= 8'h00;
                pcm_strobe     <= 1'b1;
            end else begin
                pcm_strobe_cnt <= pcm_strobe_cnt + 1'b1;
                pcm_strobe     <= 1'b0;
            end
        end
    end

    // =========================================================================
    // CORE INTERCONNECT SIGNALS
    // =========================================================================

    // pdm_decimator → fft_engine
    logic signed [15:0]  pcm_data;
    logic                pcm_valid;

    // fft_engine → spi_slave
    logic                faw_detected;
    logic                faw_pulse;

    // fft_engine diagnostic outputs (tied off — available for debug probing)
    logic [15:0]         mag_out;
    logic [7:0]          bin_index;
    logic                bin_valid;

    // spi_slave → fft_engine (threshold configuration)
    logic [15:0]         faw_threshold;
    logic                threshold_valid;

    // =========================================================================
    // CORE INSTANTIATIONS
    // =========================================================================

    // ── Core 1: PDM Decimator ─────────────────────────────────────────────────
    pdm_decimator u_pdm_decimator (
        .clk       (clk_12mhz),
        .rst_n     (rst_n),
        .pdm_data  (pdm_data),
        .pcm_out   (pcm_data),
        .pcm_valid (pcm_valid)
    );

    // ── Core 2: FFT Engine + FAW Detector ────────────────────────────────────
    fft_engine u_fft_engine (
        .clk          (clk_12mhz),
        .rst_n        (rst_n),
        .pcm_in       (pcm_data),
        .pcm_valid    (pcm_valid),
        .mag_out      (mag_out),
        .bin_index    (bin_index),
        .bin_valid    (bin_valid),
        .faw_detected (faw_detected),
        .faw_pulse    (faw_pulse)
    );

    // ── Core 3: SPI Slave + IRQ Controller ───────────────────────────────────
    spi_slave u_spi_slave (
        .clk              (clk_12mhz),
        .rst_n            (rst_n),
        .spi_sck          (spi_sck),
        .spi_mosi         (spi_mosi),
        .spi_miso         (spi_miso),
        .spi_csn          (spi_csn),
        .faw_detected     (faw_detected),
        .faw_pulse        (faw_pulse),
        .fpga_irq         (fpga_irq),
        .faw_threshold_out(faw_threshold),
        .threshold_valid  (threshold_valid)
    );

endmodule

`default_nettype wire
